---
- name: Verify baseline_mac
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert AppArmor is installed (Debian)
      ansible.builtin.assert:
        that:
          - "'apparmor' in ansible_facts.packages"
        fail_msg: "AppArmor package is not installed"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check SELinux status (RedHat)
      ansible.builtin.command: getenforce
      register: baseline_mac_selinux_status
      changed_when: false
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Assert SELinux is not disabled (RedHat)
      ansible.builtin.assert:
        that:
          - baseline_mac_selinux_status.stdout in ['Enforcing', 'Permissive']
        fail_msg: "SELinux is Disabled"
      when: ansible_facts['os_family'] == 'RedHat'
