---
- name: Ensure sudo is installed (RedHat)
  ansible.builtin.dnf:
    name: sudo
    state: present

- name: Ensure wheel group exists (RedHat)
  ansible.builtin.group:
    name: wheel
    state: present
