---
galaxy_info:
  role_name: baseline_logging
  author: kriolu-kloud
  description: Configures journald limits and rsyslog. Optionally forwards to a remote syslog server.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"
    - name: Amazon
      versions:
        - all
  galaxy_tags:
    - baseline
    - linux

dependencies: []
