---
galaxy_info:
  role_name: baseline_mac
  author: kriolu-kloud
  description: Manages AppArmor on Debian and SELinux on RedHat. Defaults to permissive mode to avoid breaking apps.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"
    - name: Amazon
      versions:
        - all
  galaxy_tags:
    - baseline
    - linux

dependencies: []
